### ISSUE TITLE
What happens to Console Output?

### ISSUE THREAD

**Issue by stripathi669** [tomcat-slf4j-logback/tomcat-slf4j-logback#116]
By default, all console output is logged into a file called `logs\catalina.out`.

If I'm using your library, any method to relay those logs to default `catalina.log.*` files?

If it still gonna go to `catalina.out`, can it be rolled?

**Comment by hazendaz** [comment]
This wrapper libraury is default configured to behave just like tomcat.  You can adjust as needed via the logback xml files.

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Oct 6, 2016 at 9:07 AM -0400, "stripathi669" <notifications@github.com<mailto:notifications@github.com>> wrote:


By default, all console output is logged into a file called logs\catalina.out.

If I'm using your library, any method to relay those logs to default catalina.log.* files?

-

**Comment by stripathi669** [comment]
Any inputs on how to do the needed? As redirect console output to *.log files.

**Comment by hazendaz** [comment]
In the logback.xml file, look at this entry...

```xml
    <appender name="CONSOLE" class="org.apache.juli.logging.ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} %-5level {%thread} [%logger{20}] : %msg%n</pattern>
        </encoder>
    </appender>
```

Change that to match the others indicating where you want the 'catalina.out' to instead go to 'catalina.log'.  That will capture all console output to the locaton you are after.

**Comment by hazendaz** [comment]
Better answer...tomcat by default is using catalina.out.  You can force writing away by deleting the CONSOLE appender I noted above and by setting the root logger differently in the logback.xml.

```
    <root level="INFO">
        <appender-ref ref="FILE-CATALINA" />
    </root>
```

Not certain why you might want to do this as its a tad different than the way tomcat works.  You will still end up with a logger for catalina.out but it will be empty doing this.  I'm going to close this issue.  If you feel others might be interested in this configuration please write up a markdown doc and submit a pull request under a docs/ directory with motivation as to why one might want this style of configuration.

**Comment by hazendaz** [comment]
Oh and I would add, the original idea I tossed out likely would have rolled without issue.

**Comment by hazendaz** [comment]
Reopening issue as I didn't clearly understand the original concern.  After a couple of years with logs in backup location, I clearly see that catalina.out is still populated heavily and never roles.  Deeper looking into tomcat seems to indicate that the system out is set to catalina.out rather hard and we are probably not addressing it in any good way.  I'm reviewing this now and wanted to note this is likely an issue...

**Comment by hazendaz** [comment]
See [here](http://tomcat.10.x6.nabble.com/Tomcat-catalina-out-log-is-not-folling-using-log4j-DailyRollingFileAppender-td5042745.html)

**Comment by hazendaz** [comment]
Closing again as this is not an issue with this framework.  For other libraries including tomcat, it will use system out and there is nothing this library can do to catch it.  Instead, to do so you would need to write a tomcat lifecycle listener that attempts to write it out.  That however will only get you so far as other third parties can force logging back to system out unfortunately.
