### ISSUE TITLE
Define license of project

### ISSUE THREAD

**Issue by skabashnyuk** [tomcat-slf4j-logback/tomcat-slf4j-logback#145]
Here https://github.com/tomcat-slf4j-logback/tomcat-slf4j-logback/blob/master/pom.xml#L86-L105 I can see a list of license that comes from upstream projects. But neither in source code neither in README.md I can't find that the license of tomcat-slf4j-logback project itself. Could you please clarify this in source code or README.md.

**Comment by hazendaz** [comment]
I'll have to do a little bit of research to determine based on our rebundling what license we should in fact be using.

**Comment by skabashnyuk** [comment]
Hi @hazendaz  any progress with this task?  Is there any chance that your work will be with EPL compatible license https://eclipse.org/legal/eplfaq.php#3RDPARTY I would like to reuse your ideas in one of Eclpse's project.

**Comment by hazendaz** [comment]
Thanks @skabashnyuk After looking that seems like the most appropriate license given we cover apache, epl, and mit license for the rebundling.  So I'll make it as that license shortly.  Thanks.
