### ISSUE TITLE
Tomcat 8.5.20

### ISSUE THREAD

**Issue by johnblaut** [tomcat-slf4j-logback/tomcat-slf4j-logback#186]
Would it kindly be possible to build a new release for recent Tomcat version 8.5.20?
Thanks in advance.

John

**Comment by hazendaz** [comment]
I'll work on a release tonight.  Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
I released tomcat 8.0.19 and 9.0.0.M25 to sonatype so those should show in central in a few hours.  I had missed releasing in that channel last time around.

I posted releases for 7.0.81, 8.0.46, 8.5.20, and 9.0.0.M26 to github [releases](https://github.com/tomcat-slf4j-logback/tomcat-slf4j-logback/releases]

I have also pushed those to sonatype as well and they should show up in a couple of ours on maven central.
