### ISSUE TITLE
Using Bitnami's Tomcat stack?

### ISSUE THREAD

**Issue by CSBaum** [tomcat-slf4j-logback/tomcat-slf4j-logback#187]
Has anyone had any success getting this to work using one of Bitnami's tomcat stack images?

I tried unzipping the contents as instructed and I can see that the logging has changed, however, it looks like it's ignoring the logback.xml file and dumping everything out at debug.

Thanks in advance for any insight on this!

Sean

**Comment by hazendaz** [comment]
I'm not familar with that stack.  Can you add a link to it?  I'll take a look when I can.

**Comment by CSBaum** [comment]
Thanks!

Here is the link, https://bitnami.com/stack/tomcat

**Comment by hazendaz** [comment]
@CSBaum I would check with that vendor.  I tested it and the tomcat build itself has no issues and if you start it natively using tomcats scripts in their builds it works fine (ie bypasing bitnami starter).  What they appear to be doing is setting the logging file location in probably some hard-coded way as I cannot find where that configuration is.  That is the problem.  As long as it is attempting to tell tomcat where it's log file is located, juli logging still attempts to apply.  This is very easily seen after removing it from the bin/setup.bat and bin/service.bat.  Presumably that is the only place they defined it.  If you use psi-probe as a drop in, you can see all the parameters passed into the application and it still contains the location reference to logging.properties.  So you just need to figure out where that reference is being stored to make this work.

**Comment by CSBaum** [comment]
Thank you!  I will ping Bitnami to see what they saw :)
