### ISSUE TITLE
Windows characters in 'setenv.sh'

### ISSUE THREAD

**Issue by tzofia** [tomcat-slf4j-logback/tomcat-slf4j-logback#195]
The file 'setenv.sh' contains '\r\n' instead of '\n', so the current configuration doesn't work on Linux :disappointed:

**Comment by hazendaz** [comment]
Thanks for the report.  I'll look into fixing it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
@tzofia Fix is on #196 and will be merged shortly.  Can you build from master and try it out to see if it solves your needs?

**Comment by tzofia** [comment]
@hazendaz Looking good! Thanks!

**Comment by hazendaz** [comment]
@tzofia Thanks for confirming.
