### ISSUE TITLE
Not possible to add access logging appenders?

### ISSUE THREAD

**Issue by rbjorklin** [tomcat-slf4j-logback/tomcat-slf4j-logback#213]
I'm trying to send our access logs to a Graylog instance with the following configuration:

```xml
...
<appender name="GELF" class="biz.paluch.logging.gelf.logback.GelfLogbackAppender">
        <host>udp:graylog.dev.company.com</host>
        <version>1.1</version>
        <extractStackTrace>true</extractStackTrace>
        <additionalFields>
            service=application-tomcat-access,version=3.40.5,organization=test,cluster=test
        </additionalFields>
    </appender>

    <appender name="ASYNC_GELF" class="ch.qos.logback.classic.AsyncAppender">
        <neverBlock>true</neverBlock>
        <queueSize>512</queueSize>
        <appender-ref ref="GELF" />
    </appender>

    <appender-ref ref="ACCESS-LOG" />
    <appender-ref ref="ASYNC_GELF" />
```

However the `<appender-ref ref="ASYNC_GELF" />` seems to be completely ignored for access-logging but works for the application hosted by Tomcat. What am I missing?

On a related note I can't find any documentation for [logback](https://logback.qos.ch/manual/configuration.html) where the `<appender-ref>` tag is used/allowed directly under the `<configuration>` tag. Is this using some custom solution?

**Comment by hazendaz** [comment]
@rbjorklin You need to look into [logback-access](https://logback.qos.ch/access.html).  It's provided by that team.  There is nothing custom here.  All this project here is doing is showing how to confirme logback-access and then changing out packaging so that tomcat-juli goes to slf4j/logback.

**Comment by hazendaz** [comment]
Closing as this is unrelated to this project.  Access logs are entirely provided by logback project and there is no relation between the two here development wise so unable to further help.  Please refer to logback-access project directly and hopefully Ceki will help out as he owns that.
