### ISSUE TITLE
Stdout log format

### ISSUE THREAD

**Issue by dataform** [tomcat-slf4j-logback/tomcat-slf4j-logback#217]
Great library, many thanks for making tomcat logging much better.
This isn't an issue but a query. How do I change the log pattern of the logback messages. i.e. these appear in stdout but I'm not sure where to configure their pattern:
`19:13:20,935 |-INFO in org.apache.juli.logging.ch.qos.logback.classic.LoggerContext[default] - Found resource [C:\opt\tomcat90\conf\logback.xml] at [file:/C:/opt/tomcat90/conf/logback.xml]
19:13:20,995 |-INFO in org.apache.juli.logging.ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [org.apache.juli.logging.ch.qos.logback.core.ConsoleAppender]
`

**Comment by hazendaz** [comment]
You don't on ones going to stdout/stderr as those are not controlled by tomcat nor logback.  You would need to write your own collector and attempt to redirect that output.  I've done such a thing but its not very useful as any library can simply change the redirect.  For the ones that are controlled, you set then in the logback.xml file as you see in your example and follow directions at logbacks website for configuration of the file.  The bit that ships with this is just emulating as closely to how tomcat works out of the box as possible.
