### ISSUE TITLE
Missing critical line in logback-access config

### ISSUE THREAD

**Issue by carlos-ouyang** [tomcat-slf4j-logback/tomcat-slf4j-logback#218]
I was following standard instructions to configure tomcat 7.0.86, 
everything was okay but access log.
finally, I found it's a missing line in logback-access.xml:
`<statusListener class="ch.qos.logback.core.status.OnConsoleStatusListener" />`

Please refer to official recommendation:
[https://logback.qos.ch/access.html#configuration](url)

**Comment by hazendaz** [comment]
Done in next release set which will hit tomcat 9 and 8.5 first.
