### ISSUE TITLE
Releases for new tomcat builds

### ISSUE THREAD

**Issue by kasecato** [tomcat-slf4j-logback/tomcat-slf4j-logback#238]
Hi!

Could you please build new releases for recent versions of Tomcat?
8.5.37
9.0.14

**Comment by hazendaz** [comment]
Already [here](https://github.com/tomcat-slf4j-logback/tomcat-slf4j-logback/releases)

I haven't released to maven central yet.  I'll probably break this project into the individual tomcat pieces before I do that as it's always been a strugle to release to central as I end up waiting until tomcat gets each module released.  Sometimes that works out but other times I have to run fully releases to get pieces to central.

**Comment by kasecato** [comment]
Thanks to your explanation, I now understand!

**Comment by hazendaz** [comment]
8.5.37 and 9.0.14 released.  These will be in central in next few hours.  I'm also working on 8.5.38 and 9.0.16 sometime in next day or so.
