### ISSUE TITLE
How to change the encoder

### ISSUE THREAD

**Issue by nicorbes** [tomcat-slf4j-logback/tomcat-slf4j-logback#260]
Hi guys, I wonder how could I use the `net.logstash.logback.encoder.LogstashEncoder` encoder on your logback.xml configuration file...

How to include the classes into the tomcat-juli.jar?

Thanks in advance!

**Comment by hazendaz** [comment]
It seems to me that encoder is more for usage when writing the logs that would expect a format like json.  This library is internal to tomcats current usage and would not make use of the logging.  I'm not sure what value that would bring here.  Although I'm open to more discussion on this.  A possible PR and/or overview of how this would be beneficial would be of a big help.

Adding link here to [logstash encoder](https://github.com/logstash/logstash-logback-encoder)

**Comment by nicorbes** [comment]
Thanks for the quick answer... I could solved this yesterday but I have it running now, nothing like giving some extra time to the ideas.

A little of context... we are migrating our platform to MSA and all new components are made with Spring Boot. But we still have our monolith that is deployed on tomcat 8.5.47. My first reaction, and that is way I run into your project, was to convert our monolith logging (even tomcat logging) to logback and have the same logging that SB is using.

The whole solution is deployed over K8s. And now we are pushing it a little further, consolidating all the pod's logs on ELK.

In order to do that we prefer to have a pre-parsed log in JSON format instead of the plain ones created by Pattern Layout. It is easy that way to send it to logstash directly, avoiding all the RegEx parsing... 

Do you know a different approach for this?

**Comment by hazendaz** [comment]
That makes perfect sense.  Since the logstash encoder is currently written to support using logback directly, I think it would require building out a separate copy of the logstash module that uses the tomcat-slf4j-logback library (just import differences).  That could be accomplished in similar way using maven to do the work without additional coding.  Part of what is going on with this library and tomcat in general is to avoid conflicts if different libraries are later used for logging.  So the extras like jackson probably wouldn't hurt anything by simply being in the tomcat/lib.  I'm not sure how much work that would be but I do think it's possible to build such support.

**Comment by nicorbes** [comment]
I couldn't make it with the libraries on the lib folder... but it works perfectly fine following the same approach you use for logback jars... I just include the encoder and json libraries in the tomcat-juli ;)

Thanks!

**Comment by alins** [comment]
sorry, how exactly have you made this work @nicorbes ? 

tomcat-juli in question has the following structure (unless i'm looking at the wrong file?)...never mind the versions there

```   
 bin/
 conf/
 src/
 lib/
 LICENSE                 
 LICENSE-logback.txt     
 LICENSE-slf4j.txt       
 LICENSE-tomcat.txt      
 bin/setenv.bat          
 bin/setenv.sh           
 conf/logback-access.xml  
 conf/logback.xml        
 conf/server.xml         
 bin/tomcat-juli.jar     
 src/tomcat-juli-sources.jar  
 lib/logback-core-1.3.0-alpha5.jar  
 lib/logback-access-1.3.0-alpha5.jar  
```   

so you just added logstash-logback-encoder and logback-jackson jars to the lib folder and package back? doesn't seem right..i'm missing something

**Comment by alins** [comment]
ooo...i figure it out. so the pom file in the parent project needs to be changed a bit to include the encoder and json libraries.

any chance you can another module project for logstash @hazendaz ?

**Comment by hazendaz** [comment]
If a PR is raised, certainly..

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rohitpas** [comment]
@alins / @nicorbes I was able to add logback json encoder and related dependencies in tomcat-juli.jar (#20) and I can see tomcat console logs published in Elk stack(Kibana). But I want to send the application logs to elk. Application is bundled as war file and deployed in tomcat. 
What needs to be configured in $CATALINA_HOME/conf/logback.xml to get the application logs 
or do I need separate logback.xml in application war file?
FYI application is using old log4j for loggings and logs are generated in local files.

**Comment by hazendaz** [comment]
There are really 3 spots for configuration. 

- bin/conf with tomcat-juli is separate entirely as tomcat uses different imports so it does not conflict at all.
- lib that would affect the entire application and all wars (you can add logback.xml there and the jars which will affect all wars)
- webapps so it only individually affects

If running tomcat with single application, the lib is where you want to place things to ensure all is using slf4j/logback.  If underlying wars are using other loggers though you would need to strip those out to pull that off.
