### ISSUE TITLE
[QUESTION] How can i customize the catalina.out with logback ?

### ISSUE THREAD

**Issue by p4535992** [tomcat-slf4j-logback/tomcat-slf4j-logback#262]
How can i customize the catalina.out with logback ?

i just want to change the level from DEBUG to INFO for  the package `org.apache.catalina` on the `catalina.out` file...

so i added this line to the logback, but i guess i missing something...

```
  <logger name="org.apache.catalina" level="INFO"/>
```

but i still see on the file catalina.out all the debug logs from the package  `org.apache.catalina` what i'm doing wrong ?

**Comment by hazendaz** [comment]
Hi @p4535992, quite simply, you don't control that file.  That is stderr/stdout.  See https://stackoverflow.com/questions/8119745/why-file-is-named-catalina-out.  Logback in no way can control that file.

**Comment by p4535992** [comment]
Ty
